version: 2.1

jobs:
  sonarqube:
    docker:
      - image: sonarsource/sonar-scanner-cli
    resource_class: small
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            cd backend
            npm install
      - run:
          name: Start server in background
          command: |
            cd backend
            npm run dev &
      - attach_workspace:
          at: ~/workspace
      - run:
          name: SonarQube Analysis
          command: |
            cd Backend
            SONAR_BRANCH="${CIRCLE_BRANCH:-master}"
            echo "Sonar branch value is: " $SONAR_BRANCH
            echo "Sonar org value is : "$SONAR_ORG
            sonar-scanner \
            -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
            -Dsonar.organization="$SONAR_ORG" \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.exclusions="/android/,/ios/" \
            -Dsonar.login="$SONAR_TOKEN" \
            -Dsonar.branch.name="$SONAR_BRANCH" \
            -Dsonar.sources="." \
            -Dsonar.c.file.suffixes=- \
            -Dsonar.cpp.file.suffixes=- \
            -Dsonar.objc.file.suffixes=-

  newmantest:
    docker:
      - image: cimg/node:18.20.2
    resource_class: small
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            cd backend
            npm install
      - run:
          name: Start backend server
          command: |
            cd backend
            npm run dev &
      - run:
          name: Wait for backend server
          command: sleep 10
      - attach_workspace:
          at: ~/workspace


workflows:
  version: 2
  sonar_workflow:
    jobs:
      - sonarqube
