# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define jobs
jobs:
  build-and-prepare:
    docker:
      - image: circleci/node:18
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build the project
          command: npm run build  # Ensure this command outputs to /build
      - persist_to_workspace:
          root: ~/build
          paths:
            - .

  sonarqube:
    working_directory: ~/build
    docker:
      - image: sonarsource/sonar-scanner-cli
    resource_class: small
    steps:
      - attach_workspace:
          at: ~/workspace
      - run:
          name: Run SonarQube analysis
          command: |
            SONAR_BRANCH="${CIRCLE_BRANCH:-master}"
            echo "Sonar branch value is: $SONAR_BRANCH"
            echo "Sonar org value is: $SONAR_ORG"
            sonar-scanner \
              -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
              -Dsonar.organization="$SONAR_ORG" \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.exclusions="**/android/**,**/ios/**" \
              -Dsonar.token="$SONAR_TOKEN" \
              -Dsonar.branch.name="$SONAR_BRANCH" \
              -Dsonar.sources="."

# Define workflows to orchestrate the jobs
workflows:
  main-workflow:
    jobs:
      - build-and-prepare
      - sonarqube:
          requires:
            - build-and-prepare
          context: SonarCloud
